<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>RSVTravelersMapForce</AssemblyName>
    <RootNamespace>RSVTravelersMapForce</RootNamespace>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GamePath>/home/diego/.wine/drive_c/Games/Stardew Valley</GamePath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Stardew Valley"><HintPath>$(GamePath)/Stardew Valley.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="StardewModdingAPI"><HintPath>$(GamePath)/StardewModdingAPI.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony"><HintPath>$(GamePath)/smapi-internal/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MonoGame.Framework"><HintPath>$(GamePath)/MonoGame.Framework.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(GamePath)/smapi-internal/Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="xTile"><HintPath>$(GamePath)/xTile.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
